apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "nagra.fullname" . }}-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvcSize }}